export const INITIAL_SAVE_COMPATIBILITY_VERSION = 1;

export const GAME_CONFIG = {
  version: 76,
  // Increment this only when a change cannot preserve the meaning of an old save.
  // A different value forces a fresh game instead of weakening the game design
  // to keep an incompatible save alive.
  saveCompatibilityVersion: INITIAL_SAVE_COMPATIBILITY_VERSION,
  initialContacts: 5,
  initialSwords: 6,
  profileNameMaxLength: 80,
  rarityOverviewEmailsSent: 10,
  socialUnlockMembers: 35,
  tournamentUnlockMembers: 6,
  tournamentMinimumMembers: 6,
  officialSwordSupplierUnlockMembers: 15,
  guaranteedAndreaContactPosition: 9,
  collaboratorAggregateUnlockCount: 9,
  conversionGuaranteeFailures: 4,
  emailOutcomeMinMs: 10_000,
  emailOutcomeMaxMs: 10_000,
  trialWaitMinMs: 30_000,
  trialWaitMaxMs: 30_000,
  trialDurationMs: 15_000,
  dayNotificationVisibilityMs: 10_000,
  progressUpdateIntervalMs: 250,
  gameTickMs: 1_000,
  minimumTrainingDurationMs: 1_000,
  instructorTrainingWhileTeachingDurationMultiplier: 3,
  sendDelayMs: 350,
  monthlyMemberFee: 40,
  monthlyMemberFormBonus: 5,
  enrollmentBonus: 20,
  shortGoalActivationBalance: 5_000,
  shortGoalReactivationDelayMs: 60_000,
  gameMonthMs: 60_000,
  secretLegendaryTrialDurationMs: 30_000,
  tutorialSparringDurationMs: 5_000,
  tutorialSparringMinimumContacts: 1,
  equipmentMaintenanceCostPerLoad: 2,
  equipmentDamagedSwordRepairCost: 250,
  equipmentAutomaticCostFactor: 0.75,
  equipmentLoadPerTrial: 2,
  equipmentLoadPerSecretLegendaryTrial: 40,
  equipmentLoadPerAgonistCourse: 20,
  equipmentBreakLoad: 100,
  eventWearMultiplier: 1,
  eventZeroContactProtectionCollaboratorThreshold: 4,
  eventContactProtectedActiveMembers: 10,
  eventContactEasyMarketMembers: 1_000,
  equipmentMaximumUpgradeWearReduction: 0.5,
  equipmentMaximumEventMasteryWearReduction: 0.25,
  officialSwordCost: 330,
  legendaryEnrollmentChancePerFailure: 0.03,
  formSevenDepartureChance: {
    common: 0.025,
    rare: 0.005,
    "ultra-rare": 0.0025,
    legendary: 0,
  },
  departureChancePerFoundedSchool: 0.005,
  collaboratorWritingPerSecond: 5,
  socialEmailWritingShare: 0.95,
  socialContentShareWhileWriting: 0.05,
  technicalArenaBaseCost: 500,
  technicalArenaDurationsMs: [120_000, 100_000, 80_000, 60_000, 40_000],
  agonistCourseBaseCost: 1_000,
  agonistCourseDurationMs: 60_000,
  lessonImprovementIntervalMs: 60_000,
  athleticPreparationFavoriteChance: 0.05,
  socialBaseContentCharacters: 100_000,
  socialBaseFollowerChance: 0.5,
  socialDoubleFollowerChance: 0.05,
  socialEventPromotionPerFollower: 0.00005,
  socialBaseFollowerValue: 0.1,
  equipmentRepairIntervalMs: 1_500,
  equipmentSwordRepairWork: 150,
  narrativeEventMinMs: 120_000,
  narrativeEventMaxMs: 300_000,
  narrativeHistoryLimit: 30,
  narrativeNegativeStreakLimit: 2,
  prestigeFame: 150,
  prestigeCollaborators: 8,
  prestigeEvents: 25,
  prestigeBonusPerSchool: 0.25,
  networkIncomePerSchool: 5,
  saveIntervalMs: 60_000,
  recentEmailsLimit: 500,
  recentCompletedTrialsLimit: 500,
  recentCompletedEventsLimit: 200,
  recentTournamentResultsLimit: 24,
  recentMissedTournamentsLimit: 48,
  chroniclesTeamSize: 6,
  chroniclesLegendaryFameReward: 500,
  reptileVenueCost: 10_000,
  reptileBasePreparationMonths: 6,
  reptileSwordRentalCost: 100,
  reptileSwordWear: 20,
  reptileMaximumGadgetGrossPerTeam: 1_000,
} as const;

export function getTechnicalArenaDurationMs(level: number): number {
  const durations = GAME_CONFIG.technicalArenaDurationsMs;
  const index = Math.max(0, Math.min(durations.length - 1, Math.floor(level) - 1));
  return durations[index] ?? durations[0];
}
