import type { EmailCatalogEntry } from "./emailTemplates";

/*
 * Le 100 email del gioco, una per idea. Si scrive solo testo corretto:
 * - draftSubject / draft: la bozza goliardica dei livelli 0–1. Gli errori del
 *   livello 0 li aggiunge il gioco (levelZeroTypos.ts), non vanno scritti qui.
 * - subject / opening / invitation: la versione curata dei livelli 2–7.
 * Le frasi aggiuntive che crescono con i potenziamenti stanno in emailPhrases.ts.
 * Segnaposto disponibili: {{firstName}} e {{senderName}}.
 */
export const EMAIL_CATALOG: EmailCatalogEntry[] = [
  {
    id: "prima-prova",
    draftSubject: "PROVA GRATIS (non è una truffa giuro)",
    draft: "Vieni a provare LudoSport, lo sport con le spade che fanno luce e tanti suoni magici. Siamo quasi tutti bravi e nessuno ha mai perso un braccio in modo definitivo per ora.",
    subject: "Una lezione di prova con l'Ordine delle Onde",
    opening: "grazie per l'interesse dimostrato durante il nostro incontro. La nostra disciplina unisce tecnica, controllo e collaborazione in un ambiente accessibile anche a chi parte da zero.",
    invitation: "Ti invitiamo a una lezione gratuita: servono soltanto abiti comodi e curiosità.",
  },
  {
    id: "disciplina-originale",
    draftSubject: "Sport strano cerca persona normale",
    draft: "Abbiamo inventato un modo elegante per correre in palestra agitando neon costosissimi. La prova è gratis, però se sei troppo forte fai finta di niente.",
    subject: "Scopri una disciplina sportiva originale a Genova",
    opening: "all'Ordine delle Onde alleniamo coordinazione, precisione e rispetto dell'avversario attraverso un'attività sportiva fuori dall'ordinario.",
    invitation: "La prima lezione è gratuita e tutto il materiale necessario viene fornito dalla scuola.",
  },
  {
    id: "sicurezza-prima",
    draftSubject: "Sicurezza circa garantita",
    draft: "Prova una disciplina diversa, con spade strane, esercizi mortali e un gruppo divergente. La prova è gratuita e non serve esperienza.",
    subject: "Sicurezza e tecnica nella tua prima lezione",
    opening: "ogni nuovo partecipante comincia dalle regole di sicurezza e dai movimenti fondamentali, seguito passo dopo passo da chi conduce la lezione.",
    invitation: "Se vuoi vedere come lavoriamo, possiamo riservarti un posto alla prossima prova.",
  },
  {
    id: "gruppo-genova",
    draftSubject: "Il gruppo di Genova non morde quasi mai",
    draft: "Siamo un gruppo accogliente, a parte Andrea quando perde e inizia a parlare in latino. Vieni a fare spadate luminose con noi, la prima botta... cioè... prova, è gratis.",
    subject: "Conosci il nostro gruppo di Genova",
    opening: "siamo un gruppo di persone con esperienze diverse, unite dal piacere di allenarsi e imparare insieme con continuità.",
    invitation: "Vieni a conoscere la scuola durante una lezione introduttiva senza impegno.",
  },
  {
    id: "coordinazione",
    draftSubject: "Hai della coordinazione da buttare?",
    draft: "Alleniamo precisione, ritmo e il non cadere sui propri piedi. Se sai camminare sei già il migliore della classe, se non lo sai vieni pure in palestra rotolando. Prova gratis.",
    subject: "Tecnica, coordinazione e una prova gratuita",
    opening: "la lezione alterna esercizi individuali, lavoro in coppia e momenti dedicati alla comprensione della tecnica.",
    invitation: "Non è richiesta alcuna esperienza precedente: la prova è pensata proprio per cominciare.",
  },
  {
    id: "dopo-evento",
    draftSubject: "Eri tu quello all'evento? Boh ciao",
    draft: "Forse ci siamo visti all'evento o forse eri uno simile. Comunque abbiamo spade luminose e una palestra. Vieni a provare da noi prima che ci dimentichiamo di nuovo.",
    subject: "Grazie per essere passato a trovarci",
    opening: "è stato un piacere incontrarti e raccontarti qualcosa della nostra scuola. Vedere una dimostrazione è utile, ma provare in prima persona chiarisce davvero l'attività.",
    invitation: "Ti aspettiamo volentieri per una lezione introduttiva gratuita.",
  },
  {
    id: "materiale-fornito",
    draftSubject: "Le spade le portiamo noi, tranquillo",
    draft: "Non vogliamo venderti niente, solo l'esperienza migliore che potrebbe capitarti. Porta scarpe e possibilmente te stesso. La prova è gratis.",
    subject: "Per la prima prova pensiamo noi all'attrezzatura",
    opening: "per partecipare non occorre acquistare o portare attrezzatura: la scuola mette a disposizione tutto ciò che serve per iniziare in sicurezza.",
    invitation: "Porta abiti comodi e ti guideremo attraverso i primi esercizi.",
  },
  {
    id: "allenamento-completo",
    draftSubject: "Palestra per muscoli e altri organi",
    draft: "Con noi alleni gambe, braccia, mente e forse anche la milza. È uno sport completo perché dopo sei rotto dappertutto. Vieni a provare gratis e porta dell'acqua, non la birra.",
    subject: "Un allenamento per corpo e concentrazione",
    opening: "questa disciplina richiede presenza, coordinazione e capacità di osservare chi si ha di fronte, con un lavoro fisico graduale e completo.",
    invitation: "Puoi sperimentarlo direttamente con una prova gratuita in palestra.",
  },
  {
    id: "prima-volta",
    draftSubject: "La prima volta non si scorda (purtroppo)",
    draft: "Partiamo dalle basi: tenere la spada dal lato giusto e non sfidare il termosifone. Non serve esperienza, infatti alcuni di noi ancora non ce l'hanno.",
    subject: "La prima volta si comincia dalle basi",
    opening: "la lezione introduttiva è costruita per chi non ha mai impugnato una spada: sicurezza, postura e movimenti fondamentali vengono spiegati con calma.",
    invitation: "Possiamo tenerti un posto al prossimo appuntamento.",
  },
  {
    id: "orari-gruppo",
    draftSubject: "Orari precisi più o meno",
    draft: "Ci alleniamo quando la palestra è aperta e qualcuno si ricorda le chiavi. Se rispondi ti diciamo l'orario vero appena lo chiediamo nel gruppo Whatsapp.",
    subject: "Vieni a conoscere gli allenamenti dell'Ordine",
    opening: "gli allenamenti seguono un percorso progressivo e il gruppo accoglie regolarmente persone interessate a provare per la prima volta.",
    invitation: "Con una tua conferma ti comunicheremo il prossimo orario disponibile.",
  },
  {
    id: "ambiente-accogliente",
    draftSubject: "Ambiente accogliente con pavimento",
    draft: "La palestra ha quattro muri, un gruppo simpatico e un distributore che ruba le monete. LudoSport è figo e divertente, vieni gratis a verificare.",
    subject: "Una palestra in cui imparare insieme",
    opening: "la qualità dell'allenamento dipende anche dall'ambiente: attenzione reciproca, rispetto e disponibilità ad aiutarsi fanno parte di ogni incontro.",
    invitation: "La lezione di prova è il modo migliore per conoscere direttamente il gruppo.",
  },
  {
    id: "controllo-movimento",
    draftSubject: "Controlla la spada prima che lei controlli te",
    draft: "Impari precisione, distanza e a fare facce molto serie mentre impugni un tubo luminoso. Sembra facile nei film, quindi vieni a essere smentito gratis.",
    subject: "Allena controllo, precisione e movimento",
    opening: "il percorso tecnico sviluppa controllo del gesto, gestione della distanza e capacità di prendere decisioni in movimento.",
    invitation: "Ti proponiamo una prima lezione guidata e completamente gratuita.",
  },
  {
    id: "nessuna-esperienza",
    draftSubject: "Non serve esperienza e si vede",
    draft: "Accettiamo principianti totali, gente confusa e chi pensa che la spada laser si ricarichi con USB. Ti spieghiamo quasi tutto. La prova è gratuita.",
    subject: "Non serve esperienza per iniziare",
    opening: "molte persone arrivano da noi senza alcuna esperienza in discipline simili. Il programma iniziale è costruito per accompagnarle in modo graduale.",
    invitation: "Se sei curioso, prenota una prova e pensa soltanto a divertirti imparando.",
  },
  {
    id: "attivita-settimanale",
    draftSubject: "Una cosa da fare invece dei compiti",
    draft: "La settimana è lunga e guardare il soffitto non conta come hobby. Vieni a duellare con noi: è sport, socialità e una scusa credibile per comprare guanti.",
    subject: "Una nuova attività per la tua settimana",
    opening: "inserire un allenamento diverso nella propria settimana può essere un buon modo per ritrovare energia e concentrazione.",
    invitation: "Vieni a verificare di persona se l'Ordine delle Onde fa per te.",
  },
  {
    id: "domande-prima",
    draftSubject: "Fai domande ma non troppo difficili",
    draft: "Puoi chiederci tutto su sicurezza, allenamenti e spade. Se non sappiamo la risposta guardiamo su internet con aria professionale. La prima prova è gratis.",
    subject: "Tutte le domande sono benvenute",
    opening: "prima di cominciare è normale avere domande su sicurezza, preparazione fisica e svolgimento della lezione. Dedichiamo sempre tempo a rispondere.",
    invitation: "Puoi venire a una prova gratuita e valutare con calma l'esperienza.",
  },
  {
    id: "percorso-progressivo",
    draftSubject: "Prima piano poi fortissimo",
    draft: "Il percorso è graduale: prima cammini, poi colpisci, poi impari perché non dovevi colpire lì. Ogni lezione aggiunge una roba nuova e qualche livido morale.",
    subject: "Un percorso tecnico costruito un passo alla volta",
    opening: "ogni lezione aggiunge competenze nuove a una base chiara, senza richiedere di imparare tutto immediatamente.",
    invitation: "La prova introduttiva ti mostrerà il primo tratto del percorso.",
  },
  {
    id: "prova-senza-impegno",
    draftSubject: "Prova senza impegno e senza notaio",
    draft: "Vieni una volta, provi le spade e poi puoi sparire nella nebbia di Genova. Non firmi niente a parte forse la presenza, se troviamo la penna. È gratis.",
    subject: "Prova gratuita e senza impegno a Genova",
    opening: "la prima partecipazione serve a conoscere persone, spazi e metodo di allenamento prima di prendere qualunque decisione.",
    invitation: "Rispondi con la tua disponibilità e organizzeremo la visita.",
  },
  {
    id: "movimento-strategia",
    draftSubject: "Scacchi ma puoi correre e urlare piano",
    draft: "È uno sport di strategia, solo che i pezzi siete voi e nessuno ricorda come si muove l'alfiere. Muoviti, pensa e fai finta che fosse tutto calcolato.",
    subject: "Movimento e strategia nello stesso allenamento",
    opening: "gli esercizi combinano gesto atletico, lettura della situazione e collaborazione con compagni sempre diversi.",
    invitation: "Ti invitiamo a sperimentare questa combinazione durante una lezione gratuita.",
  },
  {
    id: "scuola-aperta",
    draftSubject: "La scuola è aperta, la porta anche",
    draft: "Stiamo cercando nuovi partecipanti perché ormai sappiamo già tutte le battute dei vecchi. Vieni a portare idee, energia o almeno una battuta diversa.",
    subject: "La scuola è aperta a nuovi partecipanti",
    opening: "in questo periodo stiamo accogliendo persone interessate a iniziare un percorso regolare insieme al gruppo di Genova.",
    invitation: "Saremmo felici di presentarti l'attività durante la prossima prova.",
  },
  {
    id: "invito-aperto",
    draftSubject: "Invito molto ufficiale fatto dal telefono",
    draft: "Sei ufficialmente invitato all'Ordine delle Onde, nome serissimo scelto senza ridere. Porta vestiti comodi e curiosità; il mantello è facoltativo ma bello.",
    subject: "Il tuo invito all'Ordine delle Onde",
    opening: "la porta della palestra è aperta a chi vuole allenare presenza, controllo e coordinazione in un contesto accogliente.",
    invitation: "Il percorso può iniziare con una singola lezione gratuita.",
  },
  {
    id: "lunedi-luminoso",
    draftSubject: "Il lunedì fa schifo, mettiamoci una spada",
    draft: "Il lunedì sera puoi fissare il muro oppure illuminare la palestra con noi. Entrambe allenano la concentrazione ma solo una ha le spade. Prova gratis.",
    subject: "Un modo diverso di vivere il lunedì sera",
    opening: "ci sono lunedì che terminano sul divano e lunedì in cui si impara qualcosa di completamente nuovo insieme a un gruppo motivato.",
    invitation: "Noi preferiamo i secondi: vieni a provarne uno gratuitamente.",
  },
  {
    id: "curiosita-inizio",
    draftSubject: "Se hai aperto questa mail sei già qualificato",
    draft: "La curiosità basta per iniziare, insieme a due gambe opzionali e delle scarpe pulite. Al resto pensiamo noi o chiediamo a quello grande del gruppo.",
    subject: "La curiosità è già un ottimo inizio",
    opening: "non occorre sapere esattamente cosa aspettarsi. La curiosità basta per entrare in palestra; alle spiegazioni, alla sicurezza e alle spade pensiamo noi.",
    invitation: "Prenota la tua prima lezione e lascia che il resto diventi esperienza.",
  },
  {
    id: "routine-nuova",
    draftSubject: "La tua routine manca di rumori laser",
    draft: "Sveglia, lavoro, cena, noia: manca chiaramente una spada luminosa in mezzo. Vieni a sistemare la settimana con esercizi strani e persone ancora più strane.",
    subject: "La tua routine potrebbe usare una spada in più",
    opening: "una settimana ben organizzata ha spazio per lavoro, riposo e almeno un'attività capace di sorprendere davvero.",
    invitation: "Aggiungi una prova gratuita e osserva l'effetto sulla routine.",
  },
  {
    id: "precisione-divertente",
    draftSubject: "Precisione però anche casino",
    draft: "Proviamo lo stesso movimento cento volte finché viene bene o chiude la palestra. È stranamente divertente, tipo piegare le magliette ma con più duelli.",
    subject: "La precisione può essere molto divertente",
    opening: "ripetere un movimento finché diventa naturale è soddisfacente; farlo con un gruppo e una spada rende il processo decisamente più interessante.",
    invitation: "Vieni a scoprire quanto durante la prossima lezione introduttiva.",
  },
  {
    id: "serata-diversa",
    draftSubject: "Serata diversa senza prendere un aereo",
    draft: "Genova di sera offre focaccia, traffico e noi che giochiamo seriamente con le spade. Vieni a provare l'opzione meno unta, la prima lezione è gratuita.",
    subject: "Una serata diversa, senza cambiare città",
    opening: "Genova offre molti modi di passare una serata. Pochi includono tecnica, movimento e una sala piena di persone con spade luminose.",
    invitation: "La prima visita è gratuita e non richiede preparazione.",
  },
  {
    id: "sfida-accessibile",
    draftSubject: "Difficile ma non tipo matematica",
    draft: "È una sfida accessibile: all'inizio sbagli tutto ma con eleganza, poi sbagli meno e compri pantaloni più larghi. Vieni gratis, nessuno interroga.",
    subject: "Una sfida nuova, ma accessibile",
    opening: "imparare una disciplina nuova mette alla prova coordinazione e attenzione, ma un buon metodo rende ogni passaggio comprensibile.",
    invitation: "Comincia dalle basi con una lezione pensata per principianti.",
  },
  {
    id: "energia-gruppo",
    draftSubject: "Porta energia o una merendina",
    draft: "Il gruppo mette spade, spiegazioni e incoraggiamenti urlati malissimo. Tu porta energia; se non ne hai vanno bene biscotti, purché non si sbriciolino.",
    subject: "Porta energia, al resto pensa il gruppo",
    opening: "il gruppo fornisce spiegazioni, materiali e compagni di allenamento. Da parte tua serve soltanto la disponibilità a metterti in gioco.",
    invitation: "Ti teniamo volentieri un posto per la prossima prova.",
  },
  {
    id: "imparare-muovendosi",
    draftSubject: "Impara senza stare seduto che assurdità",
    draft: "Qui si impara camminando, parando e cercando di ricordarsi il nome delle mosse. Finalmente una lezione dove alzarsi dal posto non è una punizione.",
    subject: "Impara qualcosa di nuovo mentre ti muovi",
    opening: "alcune competenze si studiano seduti; altre richiedono spazio, attenzione e la soddisfazione di vedere subito un movimento migliorare.",
    invitation: "Vieni a provare la seconda categoria con noi.",
  },
  {
    id: "tempo-ben-speso",
    draftSubject: "90 minuti che sembrano 87",
    draft: "In novanta minuti impari mosse, conosci gente e scopri muscoli che non avevi autorizzato. È tempo ben speso, secondo una statistica fatta da noi.",
    subject: "Novanta minuti molto diversi dal solito",
    opening: "una lezione passa tra spiegazioni, esercizi e confronto con il gruppo, lasciando la sensazione concreta di avere imparato qualcosa.",
    invitation: "Scopri se è il modo giusto di usare una delle tue prossime serate.",
  },
  {
    id: "concentrazione-attiva",
    draftSubject: "Concentrarsi correndo è legale",
    draft: "Devi pensare mentre ti muovi, cosa che sembra impossibile ma ogni tanto riesce. È come meditare, però qualcuno tenta gentilmente di colpirti con una luce.",
    subject: "Concentrazione, ma senza stare fermi",
    opening: "la disciplina richiede attenzione continua, perché distanza, ritmo e intenzione cambiano mentre ci si muove.",
    invitation: "Una prova gratuita vale più di qualunque descrizione.",
  },
  {
    id: "gruppo-che-cresce",
    draftSubject: "Ci servono persone nuove urgentemente",
    draft: "Il gruppo cresce ma nelle foto rimaniamo sempre in tre perché gli altri arrivano tardi. Vieni a riempire lo sfondo e magari anche ad allenarti. Prova gratis.",
    subject: "Il gruppo di Genova sta crescendo",
    opening: "nuove persone portano domande, stili di apprendimento e occasioni di allenamento diverse per tutti.",
    invitation: "Se vuoi farne parte, il primo passo è una lezione introduttiva.",
  },
  {
    id: "eleganza-movimento",
    draftSubject: "Eleganza venduta separatamente",
    draft: "Ti insegniamo movimenti precisi ed eleganti. L'eleganza può arrivare dopo parecchio, nel frattempo c'è la tuta con il ginocchio un po' scolorito.",
    subject: "Quando il movimento diventa preciso",
    opening: "all'inizio ogni gesto richiede attenzione; poi coordinazione e controllo iniziano a trasformarlo in qualcosa di sorprendentemente elegante.",
    invitation: "Vieni a vedere questo percorso cominciare dalla prima lezione.",
  },
  {
    id: "prova-pratica",
    draftSubject: "Meno teoria più pew pew",
    draft: "Potremmo spiegarti lo sport per ore, ma nessuno vuole questo. Meglio darti una spada, indicare il lato giusto e vedere cosa succede controllatamente.",
    subject: "Meno teoria, più prova pratica",
    opening: "potremmo continuare a descrivere l'attività per molte righe, ma nessun testo sostituisce la sensazione del primo esercizio riuscito.",
    invitation: "Per questo preferiamo invitarti direttamente in palestra.",
  },
  {
    id: "posto-riservato",
    draftSubject: "C'è un posto libero con scritto forse tu",
    draft: "Alla prossima prova avanza un posto perché Marco ha detto forse, che vuol dire no. Te lo riserviamo senza caparra, password o sacrifici al dio della palestra.",
    subject: "C'è un posto disponibile alla prossima prova",
    opening: "abbiamo preparato una lezione introduttiva con il tempo necessario per seguire chi arriva per la prima volta.",
    invitation: "Se l'orario è compatibile, quel posto può essere tuo.",
  },
  {
    id: "allenare-decisioni",
    draftSubject: "Impara a decidere prima di martedì",
    draft: "Alleni il corpo e prendi decisioni veloci tipo paro, scappo o fingo di aver capito. Utile anche nella vita e davanti al menù della pizzeria.",
    subject: "Allena il corpo e la capacità di decidere",
    opening: "ogni esercizio richiede di osservare, scegliere e muoversi con controllo, mantenendo sempre attenzione alla persona di fronte.",
    invitation: "Prova gratuitamente questo tipo di allenamento.",
  },
  {
    id: "settimana-memorabile",
    draftSubject: "Rendi la settimana ricordabile o almeno strana",
    draft: "Tra sette giorni non ricorderai cosa hai visto online, ma forse ricorderai la volta che uno con una spada blu ti ha detto piega le ginocchia. Vieni gratis.",
    subject: "Rendi questa settimana un po' più memorabile",
    opening: "non tutte le settimane devono assomigliarsi. A volte basta inserire un'esperienza nuova nel punto giusto.",
    invitation: "Noi proponiamo una lezione, un gruppo accogliente e diverse spade pronte.",
  },
  {
    id: "inizio-semplice",
    draftSubject: "Iniziare è facile, continuare boh",
    draft: "Per iniziare basta entrare dalla porta con vestiti comodi. Noi diamo la spada e le istruzioni; alcune sono pure corrette. La prima prova non costa niente.",
    subject: "Cominciare è più semplice di quanto sembri",
    opening: "non servono acquisti, conoscenze speciali o preparazione anticipata. Si arriva, si ascoltano le regole e si comincia dalle basi.",
    invitation: "Conferma la tua presenza e penseremo all'organizzazione.",
  },
  {
    id: "disciplina-condivisa",
    draftSubject: "Impariamo insieme perché da soli no",
    draft: "Qui tutti aiutano tutti, specialmente quando nessuno ricorda la sequenza. Si sbaglia in compagnia ed è molto più professionale. Prova gratuitamente.",
    subject: "Una disciplina che si impara insieme",
    opening: "i progressi individuali crescono grazie al lavoro con il gruppo, al confronto e alla disponibilità reciproca.",
    invitation: "Vieni a conoscere le persone che rendono possibile questo percorso.",
  },
  {
    id: "invito-concreto",
    draftSubject: "Invito concreto ma la spada è plastica",
    draft: "Ecco il piano: vieni, ti presentiamo gente, impugni una spada e provi. Piano semplicissimo scritto dopo quattro riunioni e due vocali di sette minuti.",
    subject: "Un invito concreto per la prossima lezione",
    opening: "abbiamo spazio, attrezzatura e una sequenza introduttiva pronta per chi vuole capire davvero come funziona l'attività.",
    invitation: "Manca soltanto la tua conferma.",
  },
  {
    id: "buona-storia",
    draftSubject: "Potrebbe uscirne una storia decente",
    draft: "Vieni una sera e poi potrai dire ho combattuto con spade luminose in una palestra genovese. È una storia migliore di ho riordinato il cassetto.",
    subject: "Potrebbe diventare una buona storia da raccontare",
    opening: "molte passioni iniziano con una decisione piccola: accettare un invito, entrare in una sala e provare qualcosa che non era previsto.",
    invitation: "Questa può iniziare con una lezione gratuita.",
  },
  {
    id: "divano",
    draftSubject: "Il tuo divano ha paura di questa mail",
    draft: "Il divano ti vuole fermo e molle, noi ti vogliamo in palestra con una spada. Non fidarti di un mobile che raccoglie briciole da anni. Prova gratis.",
    subject: "Una proposta che il tuo divano non approverà",
    opening: "il tuo divano sostiene che questa settimana non sia il momento giusto per provare qualcosa di nuovo. Abbiamo esaminato la sua posizione e non siamo d'accordo.",
    invitation: "Vieni a conoscere l'Ordine delle Onde con una prova gratuita.",
  },
  {
    id: "agenda-spada",
    draftSubject: "Abbiamo hackerato la tua agenda (scherzo)",
    draft: "Secondo calcoli inventati hai una sera libera perfetta per LudoSport. Se non è vero sposta qualcosa di poco importante, tipo dormire o il compleanno del gatto.",
    subject: "Abbiamo trovato uno spazio libero nella tua agenda",
    opening: "tra impegni, notifiche e cose rimandate esiste probabilmente un'ora in cui potresti imparare a usare una spada in sicurezza.",
    invitation: "Ti proponiamo di occuparla con una lezione introduttiva.",
  },
  {
    id: "scarpe-comode",
    draftSubject: "Scarpe pulite, intenzioni discutibili",
    draft: "Porta vestiti comodi e scarpe pulite. Le ottime intenzioni sono facoltative, tanto dopo cinque minuti vorrai già prendere a legnate quello che spiega. Con rispetto.",
    subject: "Abiti comodi, scarpe pulite, ottime intenzioni",
    opening: "la lista per iniziare è sorprendentemente breve. Non comprende talenti segreti, mantelli o dichiarazioni solenni.",
    invitation: "Porta questi tre elementi e al resto penserà il gruppo.",
  },
  {
    id: "riunione-movimento",
    draftSubject: "Riunione senza PowerPoint finalmente",
    draft: "È una riunione dove puoi muoverti, non prendere appunti e colpire i colleghi sportivamente. Non ci sono slide, solo spade. La prova è gratis.",
    subject: "Una riunione in cui è consentito muoversi",
    opening: "abbiamo tavoli solo quando servono, nessuna presentazione di quarantadue diapositive e parecchio spazio per allenarsi.",
    invitation: "Partecipa alla prossima riunione non amministrativa dell'Ordine.",
  },
  {
    id: "mercoledi-epico",
    draftSubject: "Mercoledì 2: la vendetta",
    draft: "Il mercoledì non ha personalità, quindi gli abbiamo dato le spade luminose. Adesso è quasi epico e sicuramente meno mercoledì. Vieni a controllare.",
    subject: "Il mercoledì può ancora migliorare",
    opening: "le probabilità che una normale serata migliori dopo aver impugnato una spada luminosa sono oggetto di uno studio interno molto ottimista.",
    invitation: "Contribuisci ai dati partecipando a una prova gratuita.",
  },
  {
    id: "coordinazione-caffe",
    draftSubject: "Il caffè non migliora i tuoi riflessi",
    draft: "Bere il dodicesimo caffè non aumenta la coordinazione, ti fa solo vibrare meglio. Noi abbiamo esercizi appositi e anche dell'acqua. Vieni a provare senza farti venire un infarto.",
    subject: "La coordinazione non si ottiene soltanto col caffè",
    opening: "il caffè aiuta molte attività, ma distanza, precisione e controllo richiedono un metodo leggermente più strutturato.",
    invitation: "Abbiamo preparato quel metodo per la tua prima lezione.",
  },
  {
    id: "nessun-prescelto",
    draftSubject: "Il prescelto non ha risposto, proviamo con te",
    draft: "Non cerchiamo eroi della galassia, ci bastano principianti capaci di rispondere alle telefonate. Se non hai poteri speciali meglio, così non dobbiamo cambiare assicurazione.",
    subject: "Non cerchiamo prescelti, accettiamo principianti",
    opening: "la selezione ufficiale richiede soltanto curiosità, rispetto delle regole e disponibilità a imparare con gli altri.",
    invitation: "Se soddisfi questi severissimi requisiti, la prova è gratuita.",
  },
  {
    id: "manuale-non-incluso",
    draftSubject: "Manuale perso ma sappiamo le cose",
    draft: "Il manuale non te lo diamo perché nessuno sa se esiste, però gli istruttori spiegano tutto a voce e con gesti enormi. Funziona dal 2006 circa. Fidati di noi!",
    subject: "Il manuale è incluso nelle spiegazioni",
    opening: "non riceverai un volume di istruzioni da studiare la sera prima. Le regole arrivano in palestra, nel momento in cui servono.",
    invitation: "Tu occupati di arrivare; noi ci occupiamo della sequenza.",
  },
  {
    id: "spazio-personale",
    draftSubject: "Spazio personale difeso con eleganza",
    draft: "Impari la distanza giusta dagli altri, molto utile pure in coda alle poste. Qui però hai una spada luminosa e alle poste ci hanno chiesto di non portarla.",
    subject: "Impara a gestire lo spazio personale con precisione",
    opening: "la distanza è una cosa seria, soprattutto quando entrambe le persone stanno cercando di capire un esercizio con una spada.",
    invitation: "La prima lezione parte proprio da questo principio.",
  },
  {
    id: "progetto-segreto",
    draftSubject: "Progetto segreto inoltrato a 100 persone",
    draft: "Stiamo formando una squadra segretissima, quindi non dirlo a nessuno a parte amici, parenti e gente incontrata al bus. La parola d'ordine è prova gratis.",
    subject: "Un progetto non particolarmente segreto",
    opening: "stiamo costruendo un gruppo sempre più preparato e accogliente. Il progetto è visibile ogni settimana in palestra e non richiede autorizzazioni speciali.",
    invitation: "Puoi osservarlo da vicino durante una prova gratuita.",
  },
  {
    id: "notifica-utile",
    draftSubject: "Notifica importante forse",
    draft: "Questa mail interrompe cose più importanti per dirti che puoi provare LudoSport gratis. Ora puoi tornare ai video di procioni, ma pensaci seriamente.",
    subject: "Questa notifica potrebbe essere utile davvero",
    opening: "in mezzo a promemoria e messaggi automatici, eccone uno con un risultato concreto: una nuova esperienza sportiva a Genova.",
    invitation: "Apri metaforicamente l'allegato e vieni alla prima lezione.",
  },
  {
    id: "postura-eroica",
    draftSubject: "Schiena dritta, mantello immaginario",
    draft: "Prima impari la postura corretta, poi quella eroica con mento alto e vento inesistente nei capelli. Il mantello è vietato perché ci si inciampa.",
    subject: "La postura eroica arriva dopo quella corretta",
    opening: "prima si impara a stare in equilibrio, poi a muoversi con controllo. L'aspetto spettacolare è una conseguenza, non un requisito.",
    invitation: "Comincia dalla versione corretta durante la prova introduttiva.",
  },
  {
    id: "palestra-senza-draghi",
    draftSubject: "Controllato oggi: zero draghi",
    draft: "Abbiamo controllato tutta la palestra e non ci sono draghi, solo polvere dietro i materassi e un istruttore molto alto. Puoi venire senza armatura.",
    subject: "Palestra verificata: nessun drago presente",
    opening: "abbiamo controllato lo spazio, preparato le spade e confermato che gli unici ostacoli saranno esercizi graduali e qualche movimento nuovo.",
    invitation: "La situazione è quindi adatta a una prima lezione.",
  },
  {
    id: "livello-curiosita",
    draftSubject: "Curiosità rilevata sopra il minimo legale",
    draft: "Se stai ancora leggendo hai abbastanza curiosità per una prova. Non è un test scientifico, l'abbiamo deciso adesso, ma i risultati sembrano comodissimi.",
    subject: "Il tuo livello di curiosità sembra sufficiente",
    opening: "il sistema non richiede test d'ingresso. Una domanda sincera sull'attività è già un indicatore più che adeguato.",
    invitation: "Converti la curiosità in esperienza con una prova gratuita.",
  },
  {
    id: "impegno-ragionevole",
    draftSubject: "Avventura media senza vulcani",
    draft: "Ti proponiamo una quantità ragionevole di avventura: niente giungle o vulcani, solo una palestra, spade luminose e gente che conta ad alta voce male.",
    subject: "Una quantità ragionevole di avventura",
    opening: "non chiediamo viaggi lontani né equipaggiamento raro. La palestra è a Genova e tutte le spade tornano nell'armadio a fine lezione.",
    invitation: "Accetta l'avventura logisticamente sostenibile.",
  },
  {
    id: "modulo-entusiasmo",
    draftSubject: "Modulo entusiasmo smarrito",
    draft: "Non serve essere entusiasta subito, puoi compilare l'entusiasmo dopo aver provato. La penna però portala tu perché le nostre spariscono misteriosamente.",
    subject: "Il modulo entusiasmo può essere compilato sul posto",
    opening: "non serve preparare un discorso. È consentito arrivare prudentemente curiosi e diventare entusiasti soltanto dopo aver provato.",
    invitation: "Abbiamo riservato questa opzione alla prossima lezione.",
  },
  {
    id: "piano-b",
    draftSubject: "Piano B perché il piano A era il divano",
    draft: "Se la tua serata prevedeva divano e niente, abbiamo un piano B con movimento e spade. Se va male il divano sarà ancora lì, non è velocissimo.",
    subject: "Un ottimo piano B per la solita serata",
    opening: "se il piano A consiste nel ripetere esattamente la settimana precedente, proponiamo un'alternativa con movimento, tecnica e persone nuove.",
    invitation: "Il piano B comincia con una prova senza impegno.",
  },
  {
    id: "statistica-sorrisi",
    draftSubject: "Il 113% dei partecipanti sorride",
    draft: "Le nostre statistiche dicono che il 113% si diverte. I conti li ha fatti uno di terza media, ma è molto convinto e aveva una calcolatrice blu.",
    subject: "Le nostre statistiche indicano molti sorrisi",
    opening: "il report non è stato sottoposto a revisione accademica, ma il gruppo sembra uscire dagli allenamenti con energia e parecchi argomenti da raccontare.",
    invitation: "Puoi verificare personalmente il campione.",
  },
  {
    id: "spada-assegnata",
    draftSubject: "Una spada ha chiesto proprio di te",
    draft: "C'è una spada libera che potrebbe essere tua per una sera. Non parla davvero, quello era Matteo dietro l'armadio, ma l'invito resta valido ed è gratis.",
    subject: "Una spada potrebbe essere temporaneamente assegnata a te",
    opening: "l'ufficio attrezzatura conferma la disponibilità di materiale per una nuova persona, previa normale spiegazione delle regole di sicurezza.",
    invitation: "Conferma la prova e completeremo l'assegnazione.",
  },
  {
    id: "decisione-semplice",
    draftSubject: "Decisione facile clicca cioè rispondi",
    draft: "Puoi dire sì, no o chi siete e come avete la mia mail. Noi speriamo sì, ma anche la terza è una domanda ragionevole. La prova comunque è gratuita.",
    subject: "La decisione più semplice della settimana",
    opening: "non devi scegliere un percorso completo oggi. Devi soltanto decidere se una singola lezione gratuita merita una serata.",
    invitation: "Noi pensiamo di sì e siamo pronti a dimostrarlo.",
  },
  {
    id: "protocollo-curiosita",
    draftSubject: "Protocollo curiosità versione FINALfinal2",
    draft: "Il protocollo dice: uno, vieni in palestra; due, prendi una spada; tre, non improvvisare il quattro. Documento approvato da gente quasi maggiorenne.",
    subject: "Protocollo interno per la gestione della curiosità",
    opening: "la tua richiesta informale è stata classificata come interesse potenzialmente trasformabile in allenamento concreto.",
    invitation: "La procedura raccomandata prevede una lezione gratuita e nessun ulteriore modulo.",
  },
  {
    id: "verbale-spade",
    draftSubject: "VERBALE: le spade ci sono",
    draft: "Dopo accurato conteggio risultano parecchie spade, meno una che è forse nel bagagliaio di Sara. Ce n'è comunque una per te. Fine del verbale.",
    subject: "Verbale sintetico sulla disponibilità delle spade",
    opening: "il controllo inventario si è concluso positivamente: esiste attrezzatura sufficiente per accogliere almeno una nuova persona motivata.",
    invitation: "Ti proponiamo di associare il tuo nome a una delle disponibilità.",
  },
  {
    id: "foglio-calcolo",
    draftSubject: "Excel dice che devi venire",
    draft: "Abbiamo messo il tuo nome in un foglio di calcolo e la casella accanto è diventata verde. Nessuno sa perché, quindi per sicurezza vieni a provare.",
    subject: "Il foglio di calcolo suggerisce una prova",
    opening: "dopo un numero non necessario di formule, la colonna conclusioni restituisce un risultato sorprendentemente leggibile: dovresti venire in palestra.",
    invitation: "Possiamo trasformare la cella in un appuntamento reale.",
  },
  {
    id: "comitato-lunedi",
    draftSubject: "Delibera contro il lunedì noioso",
    draft: "Il comitato composto da me e altri due ha deciso che il lunedì necessita di spade luminose. La mozione è passata perché il terzo era in bagno.",
    subject: "Delibera del comitato per il miglioramento del lunedì",
    opening: "il comitato ha stabilito che movimento, concentrazione e spade luminose costituiscono un aggiornamento accettabile alla normale routine.",
    invitation: "La delibera entra in vigore con la tua prima lezione.",
  },
  {
    id: "ticket-esperienza",
    draftSubject: "Ticket #404: hobby non trovato",
    draft: "Abbiamo aperto un ticket perché forse ti manca un hobby strano. Soluzione proposta: LudoSport gratis. Priorità alta ma puoi rispondere con calma.",
    subject: "Ticket aperto: nuova esperienza da configurare",
    opening: "la richiesta è stata presa in carico. Mancano soltanto una data, abiti comodi e la presenza dell'utente interessato.",
    invitation: "Conferma la disponibilità per permetterci di chiudere il ticket con successo.",
  },
  {
    id: "audit-divano",
    draftSubject: "Audit concluso: il divano perde",
    draft: "Un controllo indipendente fatto da noi conferma che il divano allena poco le gambe e troppo le briciole. La palestra vince 7 a 2, dati non disponibili.",
    subject: "Audit indipendente sulle prestazioni del divano",
    opening: "l'analisi ha rilevato un'eccessiva specializzazione nel riposo e nessun contributo alla coordinazione dinamica.",
    invitation: "Si raccomanda una compensazione tramite lezione di prova.",
  },
  {
    id: "circolare-movimento",
    draftSubject: "Circolare numero boh sul movimento",
    draft: "La presente circolare comunica che muoversi con una spada è più interessante che muoversi senza. Fonte: noi ieri sera. Partecipazione gratuita.",
    subject: "Circolare n. 12: introduzione al movimento controllato",
    opening: "la circolare stabilisce che tutti i nuovi partecipanti inizino da esercizi chiari, sicuri e progressivi sotto supervisione.",
    invitation: "Puoi partecipare alla prossima applicazione pratica della circolare.",
  },
  {
    id: "budget-zero",
    draftSubject: "Preventivo professionale: € boh cioè zero",
    draft: "La prima prova costa esattamente niente, IVA compresa credo. Il nostro reparto finanza è un barattolo con due monete, quindi approfittane finché regge.",
    subject: "Preventivo approvato: costo della prima prova € 0",
    opening: "la voce di spesa relativa alla lezione introduttiva è stata verificata e rimane ostinatamente pari a zero.",
    invitation: "Il budget non sembra quindi un motivo valido per rimandare.",
  },
  {
    id: "riunione-operativa",
    draftSubject: "Convocazione operativa senza sedie",
    draft: "Sei convocato a una riunione dove stare seduti è sconsigliato e le comunicazioni avvengono anche a colpi controllati. Ordine del giorno: divertirsi.",
    subject: "Convocazione a riunione operativa senza sedie",
    opening: "l'ordine del giorno comprende sicurezza, postura, distanza e primi esercizi. La riunione si svolgerà quasi interamente in movimento.",
    invitation: "La tua partecipazione è facoltativa ma fortemente incoraggiata.",
  },
  {
    id: "allegato-invisibile",
    draftSubject: "ALLEGATO IMPORTANTE (non c'è)",
    draft: "In allegato trovi una serata diversa. Se non la vedi è perché devi venire in palestra per aprirla fisicamente. La tecnologia non è il nostro forte.",
    subject: "Allegato: una serata diversa dal solito",
    opening: "l'allegato non compare perché è composto da spazio, persone e attività fisica. Per aprirlo è necessario presentarsi in palestra.",
    invitation: "Possiamo programmare l'accesso gratuito.",
  },
  {
    id: "kpi-coordinazione",
    draftSubject: "KPI delle tue gambe in rosso",
    draft: "I KPI inventati indicano coordinazione migliorabile e livello spada troppo basso. Proponiamo una prova gratuita e un grafico che non abbiamo ancora fatto.",
    subject: "Aggiornamento KPI: coordinazione migliorabile",
    opening: "gli indicatori disponibili suggeriscono margini di crescita interessanti nella gestione di distanza, equilibrio e precisione.",
    invitation: "È disponibile un intervento formativo introduttivo senza costi.",
  },
  {
    id: "approvazione-unanime",
    draftSubject: "Invito approvato da tutti i presenti (io)",
    draft: "La commissione ha approvato all'unanimità il tuo invito. Ero l'unico presente ma tecnicamente vale. Vieni a provare, così la prossima votiamo in due.",
    subject: "Invito approvato all'unanimità",
    opening: "tutti i membri presenti, incluse alcune spade correttamente riposte, hanno espresso parere favorevole alla tua visita.",
    invitation: "Resta da individuare soltanto la data della prova.",
  },
  {
    id: "procedura-abiti",
    draftSubject: "Procedura vestiti: mettili comodi",
    draft: "Procedura ufficiale: apri armadio, ignora i jeans stretti, scegli roba comoda e arriva. Non serve stirarla, tanto dopo cinque minuti nessuno nota niente.",
    subject: "Procedura semplificata per gli abiti comodi",
    opening: "la documentazione richiesta è stata ridotta a una sola indicazione: indossa qualcosa che permetta di muoverti liberamente.",
    invitation: "Ogni altro elemento necessario sarà fornito sul posto.",
  },
  {
    id: "registro-presenze",
    draftSubject: "Nel registro c'è un buco a forma di te",
    draft: "Abbiamo una riga vuota nel registro e una penna quasi funzionante. Potremmo scriverci il tuo nome se vieni, oppure disegnare un dinosauro. Decidi tu.",
    subject: "Uno spazio vuoto nel registro presenze",
    opening: "il registro della prossima lezione contiene una riga ancora disponibile e il reparto pianificazione vorrebbe usarla in modo produttivo.",
    invitation: "Possiamo inserire il tuo nome senza alcun impegno successivo.",
  },
  {
    id: "conformita-sicurezza",
    draftSubject: "Sicurezza verificata da uno con gli occhiali",
    draft: "Abbiamo controllato la sicurezza seriamente: spade a posto, pavimento presente e nessun vulcano attivo. Il responsabile annuiva molto convinto.",
    subject: "Verifica di conformità completata",
    opening: "regole, attrezzatura e sequenza introduttiva sono state controllate. Il sistema è pronto ad accogliere una persona alla prima esperienza.",
    invitation: "Occorre soltanto confermare chi sarà quella persona.",
  },
  {
    id: "memo-precisione",
    draftSubject: "MEMO: colpisci dove volevi colpire",
    draft: "La precisione richiede pratica, altrimenti miri alla spalla e saluti una pianta. Le nostre piante sono stanche, vieni ad allenarti correttamente.",
    subject: "Memo: la precisione richiede pratica",
    opening: "la teoria sostiene che i movimenti migliorino ripetendoli con attenzione. La palestra dispone degli strumenti per verificare questa ipotesi.",
    invitation: "Sei invitato a partecipare alla sperimentazione gratuita.",
  },
  {
    id: "istanza-novita",
    draftSubject: "Richiesta novità accettata senza leggerla",
    draft: "La tua richiesta immaginaria di una settimana meno pallosa è stata approvata. La soluzione include spade, palestra e nessun rimborso perché è già gratis.",
    subject: "Istanza di novità settimanale accettata",
    opening: "la richiesta implicita di rendere la settimana meno prevedibile è stata valutata e approvata senza osservazioni.",
    invitation: "L'azione correttiva prevista è una lezione dell'Ordine delle Onde.",
  },
  {
    id: "piano-formazione",
    draftSubject: "Piano formativo scritto sul retro",
    draft: "Il piano prevede sicurezza, mosse base e pausa acqua. Sul retro c'era la lista della spesa ma l'abbiamo cancellata quasi tutta. Formazione seria.",
    subject: "Piano formativo individuale: prima voce disponibile",
    opening: "il piano può iniziare con sicurezza, fondamentali e semplici esercizi in coppia, senza prerequisiti nascosti.",
    invitation: "La prima voce del piano è offerta gratuitamente.",
  },
  {
    id: "notifica-sistema",
    draftSubject: "ERRORE: curiosità non convertita",
    draft: "Il sistema ha trovato curiosità ma zero spade impugnate. Per risolvere riavvia te stesso in palestra durante una prova. Se persiste porta biscotti.",
    subject: "Notifica di sistema: curiosità ancora attiva",
    opening: "il sistema ha rilevato che l'interesse mostrato non è ancora stato convertito in esperienza diretta.",
    invitation: "Premi metaforicamente Conferma partecipando a una prova.",
  },
  {
    id: "chiusura-pratica",
    draftSubject: "Chiudiamo sta pratica venendo in palestra",
    draft: "La pratica rimane aperta finché non provi. Ci occupa spazio sulla scrivania e qualcuno ci ha appoggiato una pizzetta. Aiutaci a chiuderla gratis.",
    subject: "Azione richiesta per chiudere la pratica",
    opening: "la pratica resta aperta finché non scopri se questa disciplina ti piace davvero. Ulteriori email non possono sostituire il test sul campo.",
    invitation: "Completa il processo con una singola lezione gratuita.",
  },
  {
    id: "rete-onde",
    draftSubject: "Unisciti alla rete, non quella del Wi-Fi",
    draft: "La rete dell'Ordine cresce una persona strana alla volta. Il Wi-Fi invece non prende negli spogliatoi, ma con una spada in mano non ti serve molto.",
    subject: "La rete cresce una persona curiosa alla volta",
    opening: "ogni scuola, gruppo e percorso tecnico comincia dall'arrivo di persone disposte a provare seriamente qualcosa di nuovo.",
    invitation: "La tua prima lezione può essere il prossimo punto della rete.",
  },
  {
    id: "cento-inviti",
    draftSubject: "Email numero 100 più o meno",
    draft: "Questo invito ha superato molti controlli qualità, tutti fatti dalla stessa persona che lo ha scritto. Non ha trovato errori per evidente conflitto di interessi.",
    subject: "Questo invito ha superato numerosi controlli qualità",
    opening: "dopo molte campagne abbiamo imparato che chiarezza, accoglienza e una prova concreta funzionano meglio di qualunque promessa esagerata.",
    invitation: "Per questo ti proponiamo semplicemente di venire in palestra.",
  },
  {
    id: "ordine-espansione",
    draftSubject: "L'Ordine si espande tipo impasto",
    draft: "Stiamo crescendo come la pizza lasciata fuori troppo, ma con meno lievito e più spade. Vieni prima che dobbiamo comprare un'altra panca. Prova gratis.",
    subject: "L'Ordine delle Onde continua ad espandersi",
    opening: "più persone significano più compagni di allenamento, più occasioni di confronto e una comunità capace di sostenere nuovi progetti.",
    invitation: "Puoi conoscere questa fase di crescita con una lezione gratuita.",
  },
  {
    id: "esperienza-consolidata",
    draftSubject: "Metodo consolidato con nastro adesivo",
    draft: "Il nostro metodo funziona da anni ed è stato aggiustato dove serviva, a volte metaforicamente e a volte col nastro. Per i principianti va una bomba.",
    subject: "Un metodo consolidato per chi comincia oggi",
    opening: "abbiamo accolto molti principianti e migliorato nel tempo spiegazioni, materiali e progressione della prima lezione.",
    invitation: "Ora quel metodo è pronto anche per te.",
  },
  {
    id: "nuova-sede-futuro",
    draftSubject: "Scuole future forse anche sulla Luna",
    draft: "Un giorno apriremo scuole ovunque, magari pure sulla Luna se l'affitto è basso. Per ora c'è Genova e ci servono persone con gravità normale.",
    subject: "Le prossime scuole iniziano dalle lezioni di oggi",
    opening: "una rete non nasce dai documenti strategici, ma dalle persone che entrano, imparano e decidono di costruire qualcosa insieme.",
    invitation: "Vieni a vedere da vicino come comincia il processo.",
  },
  {
    id: "collaborazione-reale",
    draftSubject: "Collaborazione vera, non il compito copiato",
    draft: "Qui collaborare non vuol dire copiare i compiti: vuol dire allenarsi, aiutarsi e dire bella parata anche quando era chiaramente fortuna.",
    subject: "Collaborazione reale, non soltanto una parola",
    opening: "il gruppo cresce perché le persone si allenano, si aiutano e a volte scelgono di contribuire anche all'organizzazione della scuola.",
    invitation: "La prima tappa rimane una semplice prova gratuita.",
  },
  {
    id: "forme-percorso",
    draftSubject: "Ci sono più Forme che stagioni di una serie",
    draft: "Il percorso continua oltre la prima Forma e nessuno ha ancora capito se ci sarà un finale. Ogni stagione ha mosse nuove e meno budget per gli snack.",
    subject: "Un percorso che continua oltre la prima Forma",
    opening: "le competenze si costruiscono in sequenza e aprono nel tempo possibilità diverse, senza saltare le basi che rendono tutto il resto utile.",
    invitation: "Scopri l'inizio del percorso durante la lezione introduttiva.",
  },
  {
    id: "qualita-crescita",
    draftSubject: "Cresciamo bene secondo nostra nonna",
    draft: "Il gruppo cresce ma vogliamo restare di qualità. Nostra nonna dice che siamo bravissimi e ha visto ben due video, quindi la recensione è praticamente certificata.",
    subject: "Crescere mantenendo la qualità della prima lezione",
    opening: "anche mentre il gruppo aumenta, ogni nuova persona deve ricevere tempo, spiegazioni chiare e un'esperienza sicura.",
    invitation: "Abbiamo preparato tutto questo per la tua visita.",
  },
  {
    id: "reputazione-costruita",
    draftSubject: "Reputazione ottima nel nostro gruppo chat",
    draft: "La nostra reputazione è solidissima tra le persone che già ci conoscono e hanno silenziato il gruppo. Vieni a verificare con una prova indipendente gratis.",
    subject: "La reputazione si costruisce in palestra",
    opening: "eventi e messaggi possono farci conoscere, ma sono le lezioni ben condotte e le persone soddisfatte a far crescere davvero la scuola.",
    invitation: "Ti invitiamo a valutare personalmente il nostro lavoro.",
  },
  {
    id: "generazione-contatti",
    draftSubject: "Da contatto misterioso a persona con spada",
    draft: "Ora sei un indirizzo dentro un elenco, che è tristissimo. Vieni in palestra e diventa una persona vera con nome, faccia e tecnica inizialmente discutibile.",
    subject: "Da contatto a compagno di allenamento",
    opening: "un indirizzo in elenco è soltanto l'inizio. Il passaggio importante avviene quando ci si incontra, si prova e si condivide una lezione.",
    invitation: "Trasforma questo messaggio in un incontro reale.",
  },
  {
    id: "automazione-umana",
    draftSubject: "Questa mail automatica è quasi umana",
    draft: "Un computer ha mandato la mail ma un adolescente ha scritto il testo, si nota dall'altissima qualità. Vieni a incontrare umani veri con spade finte.",
    subject: "Anche l'automazione ha bisogno di persone",
    opening: "procedure e strumenti accelerano l'organizzazione, ma il valore della scuola continua a dipendere da chi si presenta e partecipa con attenzione.",
    invitation: "Per questo il tuo posto alla prova conta ancora.",
  },
  {
    id: "evento-prossimo",
    draftSubject: "Dall'evento al posto con i materassini",
    draft: "All'evento hai visto le spade da lontano. Ora puoi vederle da vicino, forse troppo vicino ma con protezioni e spiegazioni. Prossimo passo gratuito.",
    subject: "Dall'evento alla palestra, il passo successivo",
    opening: "ci siamo incontrati fuori dalla scuola; ora puoi conoscere il contesto in cui tecnica e gruppo crescono settimana dopo settimana.",
    invitation: "Completa il percorso con una lezione introduttiva.",
  },
  {
    id: "attrezzatura-pronta",
    draftSubject: "Spade contate due volte perché sbagliavamo",
    draft: "Abbiamo controllato l'attrezzatura: tutto pronto e quasi in ordine cromatico. Manca solo qualcuno che la usi, possibilmente tu e con scarpe pulite.",
    subject: "Attrezzatura controllata, gruppo pronto",
    opening: "il registro segnala spade disponibili, usura sotto controllo e persone pronte a seguire chi comincia.",
    invitation: "È un buon momento per programmare la tua prova.",
  },
  {
    id: "social-realta",
    draftSubject: "Dal post alla realtà in bassa definizione",
    draft: "Nei video sembriamo epici grazie ai tagli giusti. Dal vivo sudiamo e sbagliamo pure, però ci divertiamo di più. Vieni a vedere la versione senza filtri.",
    subject: "Hai visto il post, ora prova la realtà",
    opening: "immagini e video mostrano soltanto una parte dell'attività. Distanza, ritmo e collaborazione si comprendono davvero solo muovendosi.",
    invitation: "Passa dalla schermata alla palestra con una prova gratuita.",
  },
  {
    id: "scuola-organizzata",
    draftSubject: "Siamo organizzatissimi da ieri",
    draft: "Calendario fatto, spade pronte, chiavi trovate: è un record. Vieni adesso prima che qualcosa torni nel bagagliaio sbagliato. Prima prova gratuita.",
    subject: "Una scuola organizzata per accoglierti",
    opening: "calendario, materiale e sequenza introduttiva sono coordinati per rendere semplice l'arrivo di una nuova persona.",
    invitation: "Scegli di presentarti; al resto penserà la procedura.",
  },
  {
    id: "dati-positivi",
    draftSubject: "I dati dicono sì ma gliel'abbiamo chiesto noi",
    draft: "Il 92% apprezza la prova e l'altro 8% non ha risposto al sondaggio perché il link era rotto. Statistica convincente no? Vieni a essere un altro numero.",
    subject: "I dati sono positivi, ma preferiamo le persone",
    opening: "conversioni e report indicano che molti partecipanti apprezzano la prova. Nessuna percentuale, però, può decidere al posto tuo.",
    invitation: "Vieni a raccogliere il dato più importante: la tua esperienza.",
  },
  {
    id: "onda-successiva",
    draftSubject: "Potresti essere l'onda o almeno una goccia",
    draft: "Ogni nuovo aiuta quello dopo, come un'onda ma con più protezioni alle ginocchia. Vieni a iniziare la prossima onda, o una piccola pozzanghera.",
    subject: "Ogni gruppo prepara l'onda successiva",
    opening: "chi ha iniziato ieri oggi aiuta i nuovi arrivati, e questa continuità rende possibile una crescita che non perde il senso del gruppo.",
    invitation: "La prossima onda può cominciare dalla tua prima lezione.",
  },
  {
    id: "programma-maturo",
    draftSubject: "Programma maturo, organizzatori meno",
    draft: "Il programma è avanzato e accoglie principianti. Noi invece ridiamo ancora se uno dice elsa, ma durante gli esercizi siamo seri almeno quasi sempre.",
    subject: "Un programma maturo che accoglie ancora principianti",
    opening: "il percorso tecnico può diventare avanzato, ma conserva sempre un ingresso chiaro per chi entra per la prima volta.",
    invitation: "Quel punto di ingresso è disponibile gratuitamente.",
  },
  {
    id: "invito-rete",
    draftSubject: "Invito ufficialissimo con timbro immaginario",
    draft: "La rete dell'Ordine ti invita ufficialmente. Il timbro non lo troviamo e la firma è questa qui sotto, però le spade esistono davvero. Prova gratis.",
    subject: "Invito ufficiale dalla rete dell'Ordine",
    opening: "la scuola di Genova continua a essere il punto di partenza per nuovi allenamenti, collaborazioni e progetti futuri.",
    invitation: "Conosci il punto di partenza durante la prossima prova.",
  },
  {
    id: "ultima-mail-prima-prova",
    draftSubject: "Ultima mail poi mandiamo un piccione",
    draft: "Abbiamo scritto, organizzato e pure trovato le chiavi. Adesso manca solo che tu venga. Se non rispondi proveremo col piccione, ma non è addestrato bene.",
    subject: "L'ultima cosa da fare è venire a provare",
    opening: "abbiamo scritto, organizzato, controllato l'attrezzatura e preparato il gruppo. Tutto ciò che poteva essere completato a distanza è completo.",
    invitation: "Resta soltanto una lezione gratuita con il tuo nome.",
  },
];
