import type { AcquisitionEventId } from "../game/types";

export interface AcquisitionEventDefinition {
  id: AcquisitionEventId;
  title: string;
  location: string;
  description: string;
  durationMs: number;
  cost: number;
  baseAttendance: number;
  demonstrationRate: number;
  contactRate: number;
  varianceMin: number;
  varianceMax: number;
  risk: "Basso" | "Medio" | "Alto";
  potential: "Molto bassa" | "Bassa" | "Media" | "Alta" | "Altissima";
  unlockMembers: number;
  requiredMembers: number;
  requiredSwords: number;
  wearAdded: number;
  contactOutcomes: readonly EventContactOutcome[];
  cooldown: EventCooldownDefinition;
}

export interface EventContactOutcome {
  weight: number;
  min: number;
  max: number;
}

export type EventCooldownDefinition =
  | { kind: "realtime"; durationMs: number }
  | { kind: "calendar"; months: number };

const STANDARD_EVENT_DURATION_MS = 10_000;

export const ACQUISITION_EVENTS: AcquisitionEventDefinition[] = [
  {
    id: "park-sparring",
    title: "Volantinaggio",
    location: "Centro di Genova",
    description: "Dei semplici flyers donati a chiunque passi per le vie della città. Pubblicità a basso costo, e qualcuno persino non li getta subito a terra!",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 0,
    baseAttendance: 6,
    demonstrationRate: 0.5,
    contactRate: 0.3,
    varianceMin: 0.8,
    varianceMax: 1.2,
    risk: "Basso",
    potential: "Molto bassa",
    unlockMembers: 0,
    requiredMembers: 0,
    requiredSwords: 0,
    wearAdded: 0,
    contactOutcomes: [
      { weight: 67, min: 0, max: 0 },
      { weight: 33, min: 1, max: 1 },
    ],
    cooldown: { kind: "realtime", durationMs: 5_000 },
  },
  {
    id: "kata-sea-waves",
    title: "Kata contro le onde del mare",
    location: "Spiaggia di Vernazzola",
    description: "Bellissimo da vedere. Ma non ci piace la sabbia. È granulosa, ruvida, irrita la pelle e si infila dappertutto.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 50,
    baseAttendance: 8,
    demonstrationRate: 0.5,
    contactRate: 0.25,
    varianceMin: 0.75,
    varianceMax: 1.25,
    risk: "Medio",
    potential: "Molto bassa",
    unlockMembers: 0,
    requiredMembers: 1,
    requiredSwords: 1,
    wearAdded: 10,
    contactOutcomes: [
      { weight: 50, min: 0, max: 0 },
      { weight: 50, min: 1, max: 1 },
    ],
    cooldown: { kind: "realtime", durationMs: 10_000 },
  },
  {
    id: "organized-flyering",
    title: "Sparring al parco",
    location: "Parco Carlo Alberto Dalla Chiesa",
    description: "Bastano due atleti, le spade che si incrociano ed i curiosi arrivano da soli. Quanti, però, non lo sa nessuno.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 250,
    baseAttendance: 12,
    demonstrationRate: 0.25,
    contactRate: 0.25,
    varianceMin: 0.35,
    varianceMax: 2.5,
    risk: "Alto",
    potential: "Molto bassa",
    unlockMembers: 5,
    requiredMembers: 2,
    requiredSwords: 2,
    wearAdded: 20,
    contactOutcomes: [
      { weight: 20, min: 0, max: 0 },
      { weight: 60, min: 1, max: 1 },
      { weight: 20, min: 2, max: 2 },
    ],
    cooldown: { kind: "realtime", durationMs: 15_000 },
  },
  {
    id: "public-demo",
    title: "Lezioni all'aperto",
    location: "Parco delle Mura",
    description: "Una lezione di prova all'aria aperta, tra alberi e panchine. Chi passa si ferma a guardare, e chi si ferma finisce per provare.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 500,
    baseAttendance: 18,
    demonstrationRate: 0.5,
    contactRate: 0.3,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Basso",
    potential: "Bassa",
    unlockMembers: 5,
    requiredMembers: 2,
    requiredSwords: 4,
    wearAdded: 30,
    contactOutcomes: [
      { weight: 50, min: 1, max: 1 },
      { weight: 50, min: 2, max: 2 },
    ],
    cooldown: { kind: "realtime", durationMs: 30_000 },
  },
  {
    id: "oktoberfest",
    title: "Oktoberfest",
    location: "Piazza della Vittoria",
    description: "Musica, stand e fiumi di birra. Il pubblico non manca; l'attenzione, dopo il terzo boccale, un po' sì.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 750,
    baseAttendance: 36,
    demonstrationRate: 0.3,
    contactRate: 0.25,
    varianceMin: 0.75,
    varianceMax: 1.3,
    risk: "Medio",
    potential: "Bassa",
    unlockMembers: 15,
    requiredMembers: 4,
    requiredSwords: 4,
    wearAdded: 40,
    contactOutcomes: [
      { weight: 50, min: 1, max: 1 },
      { weight: 50, min: 2, max: 2 },
    ],
    cooldown: { kind: "calendar", months: 1 },
  },
  {
    id: "sports-stand",
    title: "Evento sportivo",
    location: "Porto Antico",
    description: "Uno stand in mezzo a tutti gli altri sport, tra palloni e palle sudate. Tanta gente, e quasi nessuno ha mai visto una spada luminosa dal vivo.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 1_000,
    baseAttendance: 28,
    demonstrationRate: 0.35,
    contactRate: 0.28,
    varianceMin: 0.8,
    varianceMax: 1.25,
    risk: "Medio",
    potential: "Bassa",
    unlockMembers: 10,
    requiredMembers: 4,
    requiredSwords: 6,
    wearAdded: 50,
    contactOutcomes: [
      { weight: 25, min: 1, max: 1 },
      { weight: 50, min: 2, max: 2 },
      { weight: 25, min: 3, max: 3 },
    ],
    cooldown: { kind: "calendar", months: 1 },
  },
  {
    id: "local-event",
    title: "Mele Comics",
    location: "Mele",
    description: "Cosplay e fumetti per le vie del paese. Qui una spada illuminata non stupisce nessuno: sembra solo un costume particolarmente ben riuscito. Ma aspettate che inizino i combattimenti...",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 2_500,
    baseAttendance: 42,
    demonstrationRate: 0.4,
    contactRate: 0.3,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Basso",
    potential: "Media",
    unlockMembers: 20,
    requiredMembers: 6,
    requiredSwords: 8,
    wearAdded: 75,
    contactOutcomes: [
      { weight: 25, min: 1, max: 2 },
      { weight: 50, min: 2, max: 3 },
      { weight: 25, min: 3, max: 4 },
    ],
    cooldown: { kind: "calendar", months: 3 },
  },
  {
    id: "school-open-day",
    title: "CairoMix",
    location: "Cairo Montenotte",
    description: "Fumetti e cosplay nell'entroterra savonese. Qualche curva di troppo per arrivarci, ma al ritorno il bagagliaio è pieno di contatti. E di carte da gioco collezionabili che nessuno pensava di voler comprare.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 3_000,
    baseAttendance: 55,
    demonstrationRate: 0.4,
    contactRate: 0.3,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Medio",
    potential: "Media",
    unlockMembers: 35,
    requiredMembers: 8,
    requiredSwords: 10,
    wearAdded: 100,
    contactOutcomes: [
      { weight: 10, min: 1, max: 1 },
      { weight: 20, min: 2, max: 2 },
      { weight: 40, min: 3, max: 3 },
      { weight: 20, min: 4, max: 4 },
      { weight: 10, min: 5, max: 5 },
    ],
    cooldown: { kind: "calendar", months: 4 },
  },
  {
    id: "themed-event",
    title: "CogoComix",
    location: "Cogoleto",
    description: "Cosplay sul lungomare e spettacoli nel borgo. Vista mare inclusa, e stavolta la sabbia resta sulla spiaggia. Speriamo.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 5_000,
    baseAttendance: 80,
    demonstrationRate: 0.4,
    contactRate: 0.32,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Medio",
    potential: "Alta",
    unlockMembers: 60,
    requiredMembers: 10,
    requiredSwords: 12,
    wearAdded: 150,
    contactOutcomes: [
      { weight: 25, min: 3, max: 4 },
      { weight: 50, min: 5, max: 5 },
      { weight: 25, min: 6, max: 7 },
    ],
    cooldown: { kind: "calendar", months: 6 },
  },
  {
    id: "burtomics",
    title: "Burtomics",
    location: "Borgo ligure",
    description: "Un borgo storico e un pubblico che ormai ci conosce bene. Qualcuno chiede una foto, qualcuno dove ci alleniamo. I più coraggiosi chiedono quando si comincia.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 7_500,
    baseAttendance: 110,
    demonstrationRate: 0.42,
    contactRate: 0.32,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Medio",
    potential: "Alta",
    unlockMembers: 90,
    requiredMembers: 15,
    requiredSwords: 20,
    wearAdded: 200,
    contactOutcomes: [
      { weight: 25, min: 5, max: 6 },
      { weight: 50, min: 7, max: 8 },
      { weight: 25, min: 9, max: 10 },
    ],
    cooldown: { kind: "calendar", months: 12 },
  },
  {
    id: "genova-comics",
    title: "Genova Comics & Games",
    location: "Genova",
    description: "La fiera di casa, tra fumetti, giochi e ospiti illustri. Si gioca in casa, e la mamma di qualcuno è sicuramente in prima fila a fare il tifo.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 10_000,
    baseAttendance: 140,
    demonstrationRate: 0.4,
    contactRate: 0.32,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Medio",
    potential: "Alta",
    unlockMembers: 120,
    requiredMembers: 20,
    requiredSwords: 20,
    wearAdded: 250,
    contactOutcomes: [
      { weight: 25, min: 7, max: 8 },
      { weight: 50, min: 9, max: 11 },
      { weight: 25, min: 12, max: 13 },
    ],
    cooldown: { kind: "calendar", months: 18 },
  },
  {
    id: "megacon-genova",
    title: "Megacon Genova",
    location: "Fiera di Genova",
    description: "Un padiglione intero di fumetti, giochi e cosplay. Servono spade, braccia e nervi saldi: il pubblico è tanto e non ha nessuna fretta di andarsene.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 13_000,
    baseAttendance: 200,
    demonstrationRate: 0.42,
    contactRate: 0.34,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 180,
    requiredMembers: 25,
    requiredSwords: 30,
    wearAdded: 500,
    contactOutcomes: [
      { weight: 25, min: 9, max: 11 },
      { weight: 50, min: 12, max: 14 },
      { weight: 25, min: 15, max: 17 },
    ],
    cooldown: { kind: "calendar", months: 24 },
  },
  {
    id: "lucca-comics",
    title: "Lucca Comics & Games",
    location: "Lucca",
    description: "Le mura di Lucca, una folla sterminata e una coda per qualunque cosa. Con un po' di fortuna, anche davanti al nostro stand. Con un po' di sfortuna, anche per il bagno.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 15_000,
    baseAttendance: 320,
    demonstrationRate: 0.4,
    contactRate: 0.34,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 250,
    requiredMembers: 40,
    requiredSwords: 50,
    wearAdded: 750,
    contactOutcomes: [
      { weight: 25, min: 10, max: 12 },
      { weight: 50, min: 14, max: 16 },
      { weight: 25, min: 18, max: 20 },
    ],
    cooldown: { kind: "calendar", months: 30 },
  },
  {
    id: "milan-games-week",
    title: "Milan Games Week & Cartoomics",
    location: "Fiera Milano Rho",
    description: "Il palco nazionale di videogiochi e fumetti, dove ogni stand urla per farsi notare. Noi non urliamo: armiamo le spade.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 20_000,
    baseAttendance: 420,
    demonstrationRate: 0.38,
    contactRate: 0.35,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 350,
    requiredMembers: 50,
    requiredSwords: 100,
    wearAdded: 1000,
    contactOutcomes: [
      { weight: 25, min: 15, max: 17 },
      { weight: 50, min: 18, max: 22 },
      { weight: 25, min: 23, max: 25 },
    ],
    cooldown: { kind: "calendar", months: 36 },
  },
  {
    id: "cthulhu-challenge",
    title: "Sfida a Cthulhu",
    location: "R'lyeh",
    description: "Una spedizione contro l'orrore cosmico, trasmessa in mondovisione. Portate spade di scorta, nervi saldi e una buona assicurazione sulla vita. Il ritorno non è compreso nel prezzo, la sanità mentale...nemmeno.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 1_000_000,
    baseAttendance: 800,
    demonstrationRate: 0.5,
    contactRate: 0.5,
    varianceMin: 0.8,
    varianceMax: 1.2,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 500,
    requiredMembers: 1_000,
    requiredSwords: 1_000,
    wearAdded: 10_000,
    contactOutcomes: [
      { weight: 25, min: 40, max: 44 },
      { weight: 50, min: 48, max: 52 },
      { weight: 25, min: 56, max: 60 },
    ],
    cooldown: { kind: "calendar", months: 120 },
  },
];

export function getUnlockedAcquisitionEvents(fameMembers: number) {
  return ACQUISITION_EVENTS.filter((event) => event.unlockMembers <= fameMembers);
}

export function getAcquisitionEventDefinition(id: AcquisitionEventId) {
  return ACQUISITION_EVENTS.find((event) => event.id === id);
}
