import type { AcquisitionEventId } from "../game/types";

export interface AcquisitionEventDefinition {
  id: AcquisitionEventId;
  title: string;
  location: string;
  description: string;
  durationMs: number;
  cost: number;
  baseAttendance: number;
  demonstrationRate: number;
  contactRate: number;
  varianceMin: number;
  varianceMax: number;
  risk: "Basso" | "Medio" | "Alto";
  potential: "Molto bassa" | "Bassa" | "Media" | "Alta" | "Altissima";
  unlockMembers: number;
  requiredMembers: number;
  requiredSwords: number;
  wearAdded: number;
  contactOutcomes: readonly EventContactOutcome[];
  cooldown: EventCooldownDefinition;
}

export interface EventContactOutcome {
  weight: number;
  min: number;
  max: number;
}

export type EventCooldownDefinition =
  | { kind: "realtime"; durationMs: number }
  | { kind: "calendar"; months: number };

const STANDARD_EVENT_DURATION_MS = 10_000;

export const ACQUISITION_EVENTS: AcquisitionEventDefinition[] = [
  {
    id: "park-sparring",
    title: "Sparring al parco",
    location: "Parco Carlo Alberto Dalla Chiesa",
    description: "Una sessione informale e gratuita per incontrare poche persone interessate.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 0,
    baseAttendance: 6,
    demonstrationRate: 0.5,
    contactRate: 0.3,
    varianceMin: 0.8,
    varianceMax: 1.2,
    risk: "Basso",
    potential: "Molto bassa",
    unlockMembers: 0,
    requiredMembers: 0,
    requiredSwords: 2,
    wearAdded: 10,
    contactOutcomes: [
      { weight: 50, min: 0, max: 0 },
      { weight: 40, min: 1, max: 1 },
      { weight: 10, min: 2, max: 2 },
    ],
    cooldown: { kind: "realtime", durationMs: 5_000 },
  },
  {
    id: "organized-flyering",
    title: "Volantinaggio organizzato benissimo",
    location: "Centro di Genova",
    description: "Un piano impeccabile sulla carta, con risultati deliberatamente imprevedibili.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 40,
    baseAttendance: 12,
    demonstrationRate: 0.25,
    contactRate: 0.25,
    varianceMin: 0.35,
    varianceMax: 2.5,
    risk: "Alto",
    potential: "Molto bassa",
    unlockMembers: 0,
    requiredMembers: 1,
    requiredSwords: 2,
    wearAdded: 0,
    contactOutcomes: [
      { weight: 30, min: 0, max: 0 },
      { weight: 67, min: 1, max: 1 },
      { weight: 3, min: 2, max: 2 },
    ],
    cooldown: { kind: "realtime", durationMs: 10_000 },
  },
  {
    id: "public-demo",
    title: "Lezioni all'aperto",
    location: "Parco delle Mura",
    description: "Una lezione introduttiva fuori dalla palestra, semplice da organizzare e facile da notare.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 120,
    baseAttendance: 18,
    demonstrationRate: 0.5,
    contactRate: 0.3,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Basso",
    potential: "Bassa",
    unlockMembers: 5,
    requiredMembers: 2,
    requiredSwords: 4,
    wearAdded: 20,
    contactOutcomes: [
      { weight: 5, min: 0, max: 0 },
      { weight: 45, min: 1, max: 1 },
      { weight: 40, min: 2, max: 2 },
      { weight: 10, min: 3, max: 3 },
    ],
    cooldown: { kind: "realtime", durationMs: 30_000 },
  },
  {
    id: "sports-stand",
    title: "Evento sportivo",
    location: "Porto Antico",
    description: "Uno stand in una manifestazione multisport, con pubblico ampio ma interesse molto variabile.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 240,
    baseAttendance: 28,
    demonstrationRate: 0.35,
    contactRate: 0.28,
    varianceMin: 0.8,
    varianceMax: 1.25,
    risk: "Medio",
    potential: "Bassa",
    unlockMembers: 10,
    requiredMembers: 4,
    requiredSwords: 6,
    wearAdded: 40,
    contactOutcomes: [
      { weight: 54, min: 1, max: 1 },
      { weight: 36, min: 2, max: 2 },
      { weight: 10, min: 3, max: 3 },
    ],
    cooldown: { kind: "calendar", months: 1 },
  },
  {
    id: "local-event",
    title: "Mele Comics",
    location: "Mele",
    description: "Una giornata di comics, cosplay e attività sportive diffusa per le vie del paese.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 400,
    baseAttendance: 42,
    demonstrationRate: 0.4,
    contactRate: 0.3,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Basso",
    potential: "Media",
    unlockMembers: 20,
    requiredMembers: 6,
    requiredSwords: 8,
    wearAdded: 60,
    contactOutcomes: [
      { weight: 5, min: 1, max: 1 },
      { weight: 25, min: 2, max: 2 },
      { weight: 51, min: 3, max: 3 },
      { weight: 16, min: 4, max: 4 },
      { weight: 3, min: 5, max: 5 },
    ],
    cooldown: { kind: "calendar", months: 3 },
  },
  {
    id: "school-open-day",
    title: "CairoMix",
    location: "Cairo Montenotte",
    description: "Una fiera territoriale dedicata a fumetti, cosplay e cultura pop nell'entroterra savonese.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 640,
    baseAttendance: 55,
    demonstrationRate: 0.4,
    contactRate: 0.3,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Medio",
    potential: "Media",
    unlockMembers: 35,
    requiredMembers: 8,
    requiredSwords: 10,
    wearAdded: 100,
    contactOutcomes: [
      { weight: 5, min: 1, max: 1 },
      { weight: 10, min: 2, max: 2 },
      { weight: 24, min: 3, max: 3 },
      { weight: 35, min: 4, max: 4 },
      { weight: 17, min: 5, max: 5 },
      { weight: 6, min: 6, max: 6 },
      { weight: 3, min: 7, max: 7 },
    ],
    cooldown: { kind: "calendar", months: 3 },
  },
  {
    id: "themed-event",
    title: "CogoComix",
    location: "Cogoleto",
    description: "Una manifestazione sul mare con cosplay, spettacoli, stand e attività nel borgo.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 1_200,
    baseAttendance: 80,
    demonstrationRate: 0.4,
    contactRate: 0.32,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Medio",
    potential: "Alta",
    unlockMembers: 60,
    requiredMembers: 12,
    requiredSwords: 12,
    wearAdded: 150,
    contactOutcomes: [
      { weight: 13, min: 2, max: 3 },
      { weight: 29, min: 4, max: 5 },
      { weight: 41, min: 6, max: 7 },
      { weight: 13, min: 8, max: 9 },
      { weight: 4, min: 10, max: 11 },
    ],
    cooldown: { kind: "calendar", months: 6 },
  },
  {
    id: "burtomics",
    title: "Burtomics",
    location: "Borgo ligure",
    description: "Una manifestazione comics raccolta in un borgo storico, con un pubblico ormai ben riconoscibile.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 1_800,
    baseAttendance: 110,
    demonstrationRate: 0.42,
    contactRate: 0.32,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Medio",
    potential: "Alta",
    unlockMembers: 90,
    requiredMembers: 16,
    requiredSwords: 16,
    wearAdded: 200,
    contactOutcomes: [
      { weight: 11, min: 3, max: 5 },
      { weight: 25, min: 6, max: 7 },
      { weight: 39, min: 8, max: 9 },
      { weight: 20, min: 10, max: 12 },
      { weight: 5, min: 13, max: 16 },
    ],
    cooldown: { kind: "calendar", months: 6 },
  },
  {
    id: "genova-comics",
    title: "Genova Comics & Games",
    location: "Genova",
    description: "Una fiera cittadina in crescita, con aree comics, games, cosplay e ospiti del settore.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 2_600,
    baseAttendance: 140,
    demonstrationRate: 0.4,
    contactRate: 0.32,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Medio",
    potential: "Alta",
    unlockMembers: 120,
    requiredMembers: 20,
    requiredSwords: 20,
    wearAdded: 250,
    contactOutcomes: [
      { weight: 12, min: 4, max: 6 },
      { weight: 26, min: 7, max: 9 },
      { weight: 37, min: 10, max: 11 },
      { weight: 20, min: 12, max: 15 },
      { weight: 5, min: 16, max: 18 },
    ],
    cooldown: { kind: "calendar", months: 12 },
  },
  {
    id: "megacon-genova",
    title: "Megacon Genova",
    location: "Fiera di Genova",
    description: "Un grande appuntamento dedicato a fumetto, gioco, cosplay e intrattenimento pop.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 4_200,
    baseAttendance: 200,
    demonstrationRate: 0.42,
    contactRate: 0.34,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 180,
    requiredMembers: 28,
    requiredSwords: 24,
    wearAdded: 500,
    contactOutcomes: [
      { weight: 15, min: 5, max: 8 },
      { weight: 29, min: 9, max: 15 },
      { weight: 36, min: 16, max: 21 },
      { weight: 15, min: 22, max: 26 },
      { weight: 5, min: 27, max: 30 },
    ],
    cooldown: { kind: "calendar", months: 12 },
  },
  {
    id: "lucca-comics",
    title: "Lucca Comics & Games",
    location: "Lucca",
    description: "Una delle grandi manifestazioni italiane della cultura pop: pubblico enorme e logistica severa.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 7_000,
    baseAttendance: 320,
    demonstrationRate: 0.4,
    contactRate: 0.34,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 250,
    requiredMembers: 40,
    requiredSwords: 30,
    wearAdded: 700,
    contactOutcomes: [
      { weight: 18, min: 8, max: 12 },
      { weight: 20, min: 13, max: 20 },
      { weight: 25, min: 21, max: 28 },
      { weight: 24, min: 29, max: 37 },
      { weight: 13, min: 38, max: 45 },
    ],
    cooldown: { kind: "calendar", months: 24 },
  },
  {
    id: "milan-games-week",
    title: "Milan Games Week & Cartoomics",
    location: "Fiera Milano Rho",
    description: "Una manifestazione nazionale di gaming, fumetto e cultura pop che richiede una scuola molto affermata.",
    durationMs: STANDARD_EVENT_DURATION_MS,
    cost: 10_000,
    baseAttendance: 420,
    demonstrationRate: 0.38,
    contactRate: 0.35,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 350,
    requiredMembers: 50,
    requiredSwords: 36,
    wearAdded: 1000,
    contactOutcomes: [
      { weight: 17, min: 10, max: 15 },
      { weight: 22, min: 16, max: 27 },
      { weight: 25, min: 28, max: 37 },
      { weight: 24, min: 38, max: 47 },
      { weight: 12, min: 48, max: 57 },
    ],
    cooldown: { kind: "calendar", months: 24 },
  },
];

export function getUnlockedAcquisitionEvents(fameMembers: number) {
  return ACQUISITION_EVENTS.filter((event) => event.unlockMembers <= fameMembers);
}

export function getAcquisitionEventDefinition(id: AcquisitionEventId) {
  return ACQUISITION_EVENTS.find((event) => event.id === id);
}
