import type { AcquisitionEventId } from "../game/types";

export interface AcquisitionEventDefinition {
  id: AcquisitionEventId;
  title: string;
  location: string;
  description: string;
  durationMs: number;
  cost: number;
  baseAttendance: number;
  demonstrationRate: number;
  contactRate: number;
  varianceMin: number;
  varianceMax: number;
  risk: "Basso" | "Medio" | "Alto";
  potential: "Molto bassa" | "Bassa" | "Media" | "Alta" | "Altissima";
  unlockMembers: number;
  requiredMembers: number;
  requiredSwords: number;
  wearAdded: number;
}

export const ACQUISITION_EVENTS: AcquisitionEventDefinition[] = [
  {
    id: "park-sparring",
    title: "Sparring al parco",
    location: "Parco Carlo Alberto Dalla Chiesa",
    description: "Una sessione informale e gratuita per incontrare poche persone interessate.",
    durationMs: 15_000,
    cost: 0,
    baseAttendance: 6,
    demonstrationRate: 0.5,
    contactRate: 0.3,
    varianceMin: 0.8,
    varianceMax: 1.2,
    risk: "Basso",
    potential: "Molto bassa",
    unlockMembers: 0,
    requiredMembers: 0,
    requiredSwords: 2,
    wearAdded: 3,
  },
  {
    id: "organized-flyering",
    title: "Volantinaggio organizzato benissimo",
    location: "Centro di Genova",
    description: "Un piano impeccabile sulla carta, con risultati deliberatamente imprevedibili.",
    durationMs: 20_000,
    cost: 40,
    baseAttendance: 12,
    demonstrationRate: 0.25,
    contactRate: 0.25,
    varianceMin: 0.35,
    varianceMax: 2.5,
    risk: "Alto",
    potential: "Molto bassa",
    unlockMembers: 0,
    requiredMembers: 1,
    requiredSwords: 2,
    wearAdded: 2,
  },
  {
    id: "public-demo",
    title: "Lezioni all'aperto",
    location: "Parco delle Mura",
    description: "Una lezione introduttiva fuori dalla palestra, semplice da organizzare e facile da notare.",
    durationMs: 35_000,
    cost: 120,
    baseAttendance: 18,
    demonstrationRate: 0.5,
    contactRate: 0.3,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Basso",
    potential: "Bassa",
    unlockMembers: 5,
    requiredMembers: 2,
    requiredSwords: 4,
    wearAdded: 6,
  },
  {
    id: "sports-stand",
    title: "Evento sportivo",
    location: "Porto Antico",
    description: "Uno stand in una manifestazione multisport, con pubblico ampio ma interesse molto variabile.",
    durationMs: 45_000,
    cost: 240,
    baseAttendance: 28,
    demonstrationRate: 0.35,
    contactRate: 0.28,
    varianceMin: 0.8,
    varianceMax: 1.25,
    risk: "Medio",
    potential: "Bassa",
    unlockMembers: 10,
    requiredMembers: 4,
    requiredSwords: 6,
    wearAdded: 8,
  },
  {
    id: "local-event",
    title: "Mele Comics",
    location: "Mele",
    description: "Una giornata di comics, cosplay e attività sportive diffusa per le vie del paese.",
    durationMs: 50_000,
    cost: 400,
    baseAttendance: 42,
    demonstrationRate: 0.4,
    contactRate: 0.3,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Basso",
    potential: "Media",
    unlockMembers: 20,
    requiredMembers: 6,
    requiredSwords: 8,
    wearAdded: 9,
  },
  {
    id: "school-open-day",
    title: "CairoMix",
    location: "Cairo Montenotte",
    description: "Una fiera territoriale dedicata a fumetti, cosplay e cultura pop nell'entroterra savonese.",
    durationMs: 55_000,
    cost: 640,
    baseAttendance: 55,
    demonstrationRate: 0.4,
    contactRate: 0.3,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Medio",
    potential: "Media",
    unlockMembers: 35,
    requiredMembers: 8,
    requiredSwords: 10,
    wearAdded: 10,
  },
  {
    id: "themed-event",
    title: "CogoComix",
    location: "Cogoleto",
    description: "Una manifestazione sul mare con cosplay, spettacoli, stand e attività nel borgo.",
    durationMs: 60_000,
    cost: 1_200,
    baseAttendance: 80,
    demonstrationRate: 0.4,
    contactRate: 0.32,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Medio",
    potential: "Alta",
    unlockMembers: 60,
    requiredMembers: 12,
    requiredSwords: 12,
    wearAdded: 12,
  },
  {
    id: "burtomics",
    title: "Burtomics",
    location: "Borgo ligure",
    description: "Una manifestazione comics raccolta in un borgo storico, con un pubblico ormai ben riconoscibile.",
    durationMs: 65_000,
    cost: 1_800,
    baseAttendance: 110,
    demonstrationRate: 0.42,
    contactRate: 0.32,
    varianceMin: 0.85,
    varianceMax: 1.2,
    risk: "Medio",
    potential: "Alta",
    unlockMembers: 90,
    requiredMembers: 16,
    requiredSwords: 16,
    wearAdded: 13,
  },
  {
    id: "genova-comics",
    title: "Genova Comics & Games",
    location: "Genova",
    description: "Una fiera cittadina in crescita, con aree comics, games, cosplay e ospiti del settore.",
    durationMs: 70_000,
    cost: 2_600,
    baseAttendance: 140,
    demonstrationRate: 0.4,
    contactRate: 0.32,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Medio",
    potential: "Alta",
    unlockMembers: 120,
    requiredMembers: 20,
    requiredSwords: 20,
    wearAdded: 14,
  },
  {
    id: "megacon-genova",
    title: "Megacon Genova",
    location: "Fiera di Genova",
    description: "Un grande appuntamento dedicato a fumetto, gioco, cosplay e intrattenimento pop.",
    durationMs: 80_000,
    cost: 4_200,
    baseAttendance: 200,
    demonstrationRate: 0.42,
    contactRate: 0.34,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 180,
    requiredMembers: 28,
    requiredSwords: 24,
    wearAdded: 16,
  },
  {
    id: "lucca-comics",
    title: "Lucca Comics & Games",
    location: "Lucca",
    description: "Una delle grandi manifestazioni italiane della cultura pop: pubblico enorme e logistica severa.",
    durationMs: 90_000,
    cost: 7_000,
    baseAttendance: 320,
    demonstrationRate: 0.4,
    contactRate: 0.34,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 250,
    requiredMembers: 40,
    requiredSwords: 30,
    wearAdded: 18,
  },
  {
    id: "milan-games-week",
    title: "Milan Games Week & Cartoomics",
    location: "Fiera Milano Rho",
    description: "Una manifestazione nazionale di gaming, fumetto e cultura pop che richiede una scuola molto affermata.",
    durationMs: 100_000,
    cost: 10_000,
    baseAttendance: 420,
    demonstrationRate: 0.38,
    contactRate: 0.35,
    varianceMin: 0.9,
    varianceMax: 1.15,
    risk: "Alto",
    potential: "Altissima",
    unlockMembers: 350,
    requiredMembers: 50,
    requiredSwords: 36,
    wearAdded: 20,
  },
];

export function getUnlockedAcquisitionEvents(fameMembers: number) {
  return ACQUISITION_EVENTS.filter((event) => event.unlockMembers <= fameMembers);
}

export function getAcquisitionEventDefinition(id: AcquisitionEventId) {
  return ACQUISITION_EVENTS.find((event) => event.id === id);
}
